<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
	<xsl:output method="text"/>

	<xsl:include href="gensqlite.xsl"/>
	
	<xsl:template match="/">
		<xsl:text/>-- Autogenerated changeset from <xsl:value-of select="/changeset/@previous"/> to <xsl:value-of select="/changeset/@current"/> 
		<xsl:apply-templates select="*"/>
	</xsl:template>
	
	<xsl:template match="add-table">
		<xsl:apply-templates select="*"/>
	</xsl:template>

	<xsl:template match="add-column">
		<xsl:text>ALTER TABLE </xsl:text><xsl:value-of select="@table"/> ADD COLUMN
		<xsl:apply-templates select="*" mode="define"/>;
	</xsl:template>
	
	<xsl:template match="remove-table">
		<xsl:text/>DROP TABLE IF EXISTS <xsl:value-of select="@table"/>;
	</xsl:template>
</xsl:stylesheet>
